version: '3.4'

services:
  ex_18_dockerapp:
    image: ex18dockerapp:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_ex_18_dockerapp$
    volumes:
      - C:\Users\Gaspar\Documents\Visual Studio 2017\Projects\Ex_18_DockerApp\Ex_18_DockerApp:/app
      - C:\Users\Gaspar\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_ex_18_dockerapp$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_ex_18_dockerapp$ bin/Debug/netcoreapp2.0/Ex_18_DockerApp.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""
