// <auto-generated />
using Ex_Ad_14_1_EfCoreLazyLoading.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ex_Ad_14_1_EfCoreLazyLoading.Migrations
{
    [DbContext(typeof(CoffeeDbContext))]
    [Migration("20180711185102_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ex_Ad_14_1_EfCoreLazyLoading.Models.DbModels.Coffee", b =>
                {
                    b.Property<int>("CoffeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CoffeeCode")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.Property<string>("Origin");

                    b.HasKey("CoffeeId");

                    b.HasAlternateKey("CoffeeCode")
                        .HasName("APK_CoffeeCode");

                    b.HasIndex("CoffeeId", "CoffeeCode");

                    b.ToTable("Coffee");

                    b.HasData(
                        new { CoffeeId = 1, CoffeeCode = "ANTIS", Name = "Antuka", Origin = "Slovakia" },
                        new { CoffeeId = 2, CoffeeCode = "AZET", Name = "Azera", Origin = "Turkmenistan" },
                        new { CoffeeId = 3, CoffeeCode = "PERBI", Name = "PeruBio", Origin = "Peru" }
                    );
                });

            modelBuilder.Entity("Ex_Ad_14_1_EfCoreLazyLoading.Models.DbModels.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Workplace");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employee");

                    b.HasData(
                        new { EmployeeId = 1, Name = "Vlado", Workplace = "Unknown" },
                        new { EmployeeId = 2, Name = "Janči", Workplace = "KE" }
                    );
                });

            modelBuilder.Entity("Ex_Ad_14_1_EfCoreLazyLoading.Models.DbModels.EmployeeCoffee", b =>
                {
                    b.Property<int>("EmployeeCoffeeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CoffeeId");

                    b.Property<int>("EmployeeId");

                    b.HasKey("EmployeeCoffeeId");

                    b.HasIndex("CoffeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeCoffee");

                    b.HasData(
                        new { EmployeeCoffeeId = 1, CoffeeId = 1, EmployeeId = 1 },
                        new { EmployeeCoffeeId = 2, CoffeeId = 3, EmployeeId = 1 },
                        new { EmployeeCoffeeId = 3, CoffeeId = 2, EmployeeId = 2 }
                    );
                });

            modelBuilder.Entity("Ex_Ad_14_1_EfCoreLazyLoading.Models.DbModels.EmployeeCoffee", b =>
                {
                    b.HasOne("Ex_Ad_14_1_EfCoreLazyLoading.Models.DbModels.Coffee", "Coffee")
                        .WithMany("EmployeeCoffee")
                        .HasForeignKey("CoffeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Ex_Ad_14_1_EfCoreLazyLoading.Models.DbModels.Employee", "Employee")
                        .WithMany("EmployeeCoffee")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
